/home/matereza/PycharmProjects/damas-core/venv/bin/python /home/matereza/PycharmProjects/damas-core/py/async_cli/main_test.py
================================>>> test_read_many_element started
Traceback (most recent call last):
  File "/home/matereza/PycharmProjects/damas-core/py/async_cli/main_test.py", line 203, in <module>
    loop.run_until_complete(main(loop))
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/matereza/PycharmProjects/damas-core/py/async_cli/main_test.py", line 179, in main
    await test_read_many_element(ids, 10, print)
  File "/home/matereza/PycharmProjects/damas-core/py/async_cli/main_test.py", line 95, in test_read_many_element
    await asyncio.gather(*tasks)
  File "/home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py", line 179, in read
    json_result = await resp.json()
  File "/home/matereza/PycharmProjects/damas-core/venv/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 1097, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('http://localhost:8090/api/read/')
Task was destroyed but it is pending!
task: <Task pending name='Task-201' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fb24a9f0c10>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-200' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fb24a9f09d0>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-199' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fb24a9f0790>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-198' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fb24a9f0550>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-197' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fb24a9f0310>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-196' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fb24a9f00d0>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-195' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fb24a9e7e50>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-194' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fb24a9e7c10>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-193' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fb24a9e79d0>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-192' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fb24a9e7790>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-191' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fb24a9e7550>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-190' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fb24a9e7310>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-189' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fb24a9e70d0>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-188' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fb24a9dee50>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-187' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fb24a9dec10>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-186' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fb24a9de9d0>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-185' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fb24a9de760>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-184' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fb24a9de520>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-183' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fb24a9de2e0>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-182' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fb24a9de0a0>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-181' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fb24a9d4e20>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-180' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fb24a9d4be0>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-179' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fb24a9d49a0>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-178' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fb24a9d4760>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-177' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fb24a9d4520>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-176' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fb24a9d42e0>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-175' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fb24a9d40a0>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-174' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fb24a9cbe20>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-173' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fb24a9cbbe0>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-172' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fb24a9cb9a0>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-171' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fb24a9cb760>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-170' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fb24a9cb520>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-169' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fb24a9cb2e0>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-168' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fb24a9cb0a0>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-167' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fb24aa45e20>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-166' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fb24aa45be0>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-165' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fb24aa459a0>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-164' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fb24aa45760>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-163' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fb24aa45520>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-162' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fb24aa452e0>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-161' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fb24aa450a0>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-160' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fb24aa3be20>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-159' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fb24aa3bbe0>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-158' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fb24aa3b9a0>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-157' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fb24aa3b760>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-156' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fb24aa3b520>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-155' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fb24aa3b2e0>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-154' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fb24aa3b0a0>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-153' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fb24aa32e20>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-152' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fb24aa32be0>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-151' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fb24aa329a0>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-150' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fb24aa32760>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-149' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fb24aa32520>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-148' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fb24aa322e0>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-147' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fb24aa320a0>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-146' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fb24aa28e20>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-145' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fb24aa28be0>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-144' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fb24aa289a0>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-143' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fb24aa28760>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-142' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fb24aa28520>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-141' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fb24aa282e0>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-140' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fb24aa280a0>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-139' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fb24aa21e20>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-138' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fb24aa21be0>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-137' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fb24aa219a0>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-136' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fb24aa21760>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-135' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fb24aa21520>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-134' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fb24aa212e0>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-133' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fb24aa210a0>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-132' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fb24aa18e20>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-131' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fb24aa18be0>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-130' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fb24aa189a0>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-129' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fb24aa18760>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-128' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fb24aa18520>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-127' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fb24aa182e0>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-126' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fb24aa180a0>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-125' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fb24aa0fe20>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-124' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fb24aa0fbe0>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-123' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fb24aa0f9a0>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-122' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fb24aa0f760>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-121' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fb24aa0f520>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-120' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fb24aa0f2e0>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-119' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fb24aa0f0a0>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-118' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fb24aa87e20>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-117' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fb24aa87be0>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-116' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fb24aa879a0>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-115' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fb24aa87760>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-114' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fb24aa87520>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-113' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fb24aa872e0>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-112' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fb24aa870a0>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-111' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fb24aa7ce20>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-110' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fb24aa7cbe0>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-109' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fb24aa7c9a0>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-108' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fb24aa7c760>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-107' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fb24aa7c520>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-106' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fb24aa7c2e0>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-105' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fb24aa7c0a0>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-104' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fb24aa73e20>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-103' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fb24aa73be0>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>
Task was destroyed but it is pending!
task: <Task pending name='Task-102' coro=<http_async_connection.read() running at /home/matereza/PycharmProjects/damas-core/py/async_cli/damas_async.py:178> wait_for=<Future pending cb=[BaseSelectorEventLoop._sock_write_done(6, handle=<Handle BaseS....0.1', 8090))>)(), <TaskWakeupMethWrapper object at 0x7fb24aa9dd00>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.9/asyncio/tasks.py:759]>

Process finished with exit code 1
